### ISSUE TITLE
golang.org/x/net/context -> context

### ISSUE THREAD

**Issue by soh335** [schemalex/schemalex#31]
golang.org/x/net/context 使ってるのって何か理由あるんでしたっけ？

**Comment by lestrrat** [comment]
当時はまだ過渡期だったからです！ :D

**Comment by lestrrat** [comment]
やりましょうか。Go 1.9しばりでいいですよね？

**Comment by soh335** [comment]
お願いします。go 1.9 で問題ないです。（手元がまだ 1.8.1 だったことに、さっきリリースするときに気がつきましたが。

**Comment by lestrrat** [comment]
特にgo1.9-ism入れる必要なかった！

**Comment by soh335** [comment]
どもです！
